name: 'Build Ingress NGINX Images'
description: 'Build ingress-nginx controller images'
inputs:
  push:
    description: 'Push images to registry'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build images
      shell: bash
      run: |
        export TAGNGINX=$(cat images/nginx/TAG)
        export CONTROLLERTAG=$(cat TAG)
        export COMMIT_SHA=git-$(git rev-parse --short HEAD)
        export BUILD_ID="UNSET"
        export BUILDX_PLATFORM=linux/amd64
        export REGISTRY=wunderio/silta-ingress-nginx
        export NGINX_IMAGE=${REGISTRY}-base:${TAGNGINX}

        if [ "${{ inputs.push }}" == "true" ]; then
          export PUSH_FLAG=--push
          export BUILDER_FLAG=""
        else
          export PUSH_FLAG=--load
          # Use default docker driver for local builds so temporary images are accessible for subsequent builds
          export BUILDER_FLAG="--builder=default"
        fi

        echo "Building Go binaries..."
        make build ARCH=amd64 TAG=${CONTROLLERTAG}

        echo "Building NGINX Base image..."
        docker buildx build \
            ${BUILDER_FLAG} \
            ${PUSH_FLAG} \
            --progress plain \
            --platform=${BUILDX_PLATFORM} \
            -t ${NGINX_IMAGE} \
            images/nginx/rootfs

        echo "Building controller image..."
        docker buildx build \
            ${BUILDER_FLAG} \
            ${PUSH_FLAG} \
            --progress plain \
            --platform ${BUILDX_PLATFORM} \
            --build-arg BASE_IMAGE="${NGINX_IMAGE}" \
            --build-arg VERSION="${CONTROLLERTAG}" \
            --build-arg COMMIT_SHA="${COMMIT_SHA}" \
            --build-arg BUILD_ID="${BUILD_ID}" \
            -t ${REGISTRY}-controller:${CONTROLLERTAG} \
            rootfs

        echo "Building controller-chroot image..."
        docker buildx build \
            ${BUILDER_FLAG} \
            ${PUSH_FLAG} \
            --progress plain \
            --platform ${BUILDX_PLATFORM} \
            --build-arg BASE_IMAGE="${NGINX_IMAGE}" \
            --build-arg VERSION="${CONTROLLERTAG}" \
            --build-arg COMMIT_SHA="${COMMIT_SHA}" \
            --build-arg BUILD_ID="${BUILD_ID}" \
            -t ${REGISTRY}-controller-chroot:${CONTROLLERTAG} \
            rootfs -f rootfs/Dockerfile-chroot
